In [16]:
"""
MODUL 1 EXERCICI 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.
https://www.superprof.es/apuntes/escolar/matematicas/estadistica/disbidimension/coeficiente-de-correlacion.html
"""
import numpy as np
from numpy import random

import math

##############
###FUNCIONS###
##############

#funció que afageix a la matriu 3 columnes noves amb x^2, y^2 i x·y respectivament
def calcularMatriu(matriu):
    nl = len(matriu)
    nc = len(matriu[0])+3
    matriuAmbCalculs = np.empty([nl, nc], int)
    for l in range(nl):
        matriuAmbCalculs[l][0] = matriu[l][0] # x
        matriuAmbCalculs[l][1] = matriu[l][1] # y
        matriuAmbCalculs[l][2] = matriu[l][0]**2 # x^2
        matriuAmbCalculs[l][3] = matriu[l][1]**2 # y^2
        matriuAmbCalculs[l][4] = matriu[l][0] * matriu[l][1] # x·y
    return matriuAmbCalculs

#funció rota una matriu intercanviant les columnes per files i viceversa
def rotarMatriu(matriu):
    nl = len(matriu)
    nc = len(matriu[0])
    matriuRotada = np.empty([nc, nl], int)
    for l in range(nl):
        for c in range(nc):
            matriuRotada[c][l]=matriu[l][c]
    return matriuRotada

#funció que afageix una nova columna final amb els sumatoris de cada línia
def sumarMatriu(matriu):
    nl = len(matriu)
    nc = len(matriu[0])
    matriuAnexe = np.array([[0]] * nl)
    matriuAmbSumes = np.append(matriu, matriuAnexe , axis = 1)
    for l in range(nl):
        suma = sum(matriuAmbSumes[l])
        matriuAmbSumes[l][nc] = suma
    return matriuAmbSumes

#funció que comprova si la matriu és correcte (ha de tenir 2 dimensións i 2 valors a la seguna dimensió)
def matriuCorrecte(matriu):
    dimensions = len(matriu.shape)
    columnes = matriu.shape[1]
    if dimensions == 2 and columnes == 2:
        correcte = True
    else:
        correcte = False
    return correcte
    
#funció que converteix la matriu amb els calculs necessaris
def adaptarMatriu(matriu):
    matriuAdaptada = calcularMatriu(matriu)
    matriuAdaptada = rotarMatriu(matriuAdaptada)
    matriuAdaptada = sumarMatriu(matriuAdaptada)
    matriuAdaptada = rotarMatriu(matriuAdaptada)
    return matriuAdaptada
    
#funció que retorna el número de valors
def calcularNvalors(matriu):
    valors = len(matriu) - 1
    return valors
    
#funció que retorna la mitga de x o i: [0, 1]
def calcularMitga(matriu, c):
    valors = calcularNvalors(matriu)
    suma = llegirSuma(matriu, c)
    mitga = suma / valors
    return mitga

#funció que retorna la suma de la columna c
def llegirSuma(matriu, columna):
    linia = calcularNvalors(matriu)
    suma = matriu[linia][columna]
    return suma
    
#funció que retorna la desviació de la columna c
def calcularDesviacio(matriu, columna):
    suma = llegirSuma(matriu, columna + 2)
    valors = calcularNvalors(matriu)
    mitga = calcularMitga(matriu, columna)**2
    desviacio = math.sqrt((suma / valors) - mitga)
    return desviacio

#funció que retorna la desviació de la X
def calcularDesviacioX(matriu):
    columna = 0
    desviacio = calcularDesviacio(matriu, columna)
    return desviacio

#funció que retorna la desviació de la Y
def calcularDesviacioY(matriu):
    columna = 1
    desviacio = calcularDesviacio(matriu, columna)
    return desviacio

#funció que retorna la covariancia X-Y
def calcularCovariancia(matriu):
    suma = llegirSuma(matriu, 4)
    valors = calcularNvalors(matriu)
    mitga = calcularMitga(matriu, 0) * calcularMitga(matriu, 1)
    covariancia = (suma / valors) - mitga
    return covariancia

#funció que calcula el coeficient de correlació
def calcularCorrelacio(matriu):
    correlacio = calcularCovariancia(matriu) / (calcularDesviacioX(matriu) * calcularDesviacioY(matriu))
    return correlacio

#funció per mostrar una alerta
def mostrarAlerta(text):
    senefa = "-" * len(text)
    print(senefa)
    print(text)
    print(senefa)

###############
###CONSTANTS###
###############

MATRIUORIGINAL = "MATRIU ORIGINAL"
MATRIUADAPTADA = "MATRIU ADAPTADA"
CORRELACIO ="Correlació="
ERROR= "matriu no valida"

##############
###PROGRAMA###
##############

#defineixo una matriu amb dades susceptiples de correlació amb pars [x,y]
matriu = np.array([[2,14],[3,20],[5,32],[7,42],[8,44],[12,56],[15,65]])

alerta(MATRIUORIGINAL)
print(matriu)

if (matriuCorrecte(matriu)):
    matriu = adaptarMatriu(matriu)
    alerta(MATRIUADAPTADA)
    print(matriu)
    correlacio = calcularCorrelacio(matriu)
    alerta(CORRELACIO + str(correlacio))
else:
    alerta(ERROR)

---------------
MATRIU ORIGINAL
---------------
[[ 2 14]
 [ 3 20]
 [ 5 32]
 [ 7 42]
 [ 8 44]
 [12 56]
 [15 65]]
---------------
MATRIU ADAPTADA
---------------
[[    2    14     4   196    28]
 [    3    20     9   400    60]
 [    5    32    25  1024   160]
 [    7    42    49  1764   294]
 [    8    44    64  1936   352]
 [   12    56   144  3136   672]
 [   15    65   225  4225   975]
 [   52   273   520 12681  2541]]
----------------------------
Correlació=0.983678063359614
----------------------------
