In [7]:
"""
MODUL 1 EXERCICI 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.
"""

import numpy as np
from numpy import random

###############
###CONSTANTS###
###############

NMINIM = 1
NMAXIM = 10
MINIM = 0
MAXIM = 100
AVIS = "Introdueix un número natural menor o igual a " + str(NMAXIM) + "\n"
ERROR1 = "No has introduit un número, si us plau, intenta-ho de nou\n"
ERROR2 = "Ha de ser un valor entre "+str(NMINIM + 1)+" i "+str(NMAXIM)+", tos dos inclosos\n"
ERROR3 = "matriu d'una sola dimensió amb n^2 números aleatoris entre "+str(MINIM)+" i "+str(MAXIM)

##############
###PROGRAMA###
##############

numeroCorrecte = False
while not numeroCorrecte:
    #el valor del input el converteixo en int, però això fallarà si valor introduit son lletres
    #és per això que estableixo un try-catch que capturi l'error, doni un missatge d'error i torni a demanar el número
    try:
        n = int(input(AVIS))
        if n>NMINIM and n<NMAXIM:
            numeroCorrecte = True
    except ValueError:
        print(ERROR1)
        
rang = MAXIM - MINIM          
matriu = MINIM + (random.randint(rang, size = n**2))

#canvio ara la forma de la matriu a 2-D "n x n"
matriu = matriu.reshape(n, n)

print (matriu)

Introdueix un número natural menor o igual a 10
j
No has introduit un número, si us plau, intenta-ho de nou

Introdueix un número natural menor o igual a 10
j
No has introduit un número, si us plau, intenta-ho de nou

Introdueix un número natural menor o igual a 10
90
Introdueix un número natural menor o igual a 10
7
[[64 21 18 99  2  9 25]
 [85 23 56 33 29 53  4]
 [ 2 87  9 49  4 24 28]
 [84  8 61 98 22 67 38]
 [75 78 63 58 89 32 39]
 [54 81 87 77 15 98 94]
 [79 42 62 12 52 72 66]]
