In [6]:
"""
MODUL 1 EXERCICI 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.
"""

import numpy as np
from numpy import random

import statistics

##############
###FUNCIONS###
##############

#funció per mostrar títuls
def mostrarTitul(titul):
    MARGELATERAL = 10
    DECORACIO = "*"
    senefa = DECORACIO * (len(titul) + (MARGELATERAL * 2))
    senefaLateral = DECORACIO * MARGELATERAL
    text =  senefaLateral + titul + senefaLateral
    print(senefa)
    print(text)
    print(senefa)

#funció que imprimeix la suma de cada linia
def sumarLinies(matriu):
    for linia in range(matriu.shape[0]): 
        suma = sumarLinia(matriu,linia)
        mostrarSuma(LINIA, linia, suma)

#funció per sumar el total d'una linia
def sumarLinia(matriu, linia):
    return sum(matriu[linia])

#funció que imprimeix la suma de cada columna
def sumarColumnes(matriu):
    for columna in range(matriu.shape[1]):
        suma = sumarColumna(matriu, columna)
        mostrarSuma(COLUMNA, columna, suma)
    
#funció suma el total d'una columna
def sumarColumna(matriu, columna):
    suma=0;
    for linia in range(matriu.shape[0]):
        suma += matriu[linia][columna]
    return suma

#funció per mostrar resultats
def mostrarSuma(literal, index, suma):
    print (literal + str(index) + IGUAL + str(suma))

###############
###CONSTANTS###
###############

MINIM = 0 
MAXIM = 100 
NELEMENTS = 10 
LINIA = "Línia " 
COLUMNA = "Columna " 
IGUAL = " = " 
REPETICIONS = 10
MATRIUGENERADA = "MATRIU GENERADA "
SUMALINIES = "SUMA DE LÍNIES"
SUMACOLUMNES = "SUMA DE COLUMNES"

##############
###PROGRAMA###
##############

for index in range(REPETICIONS):

    nLinies = random.randint(3, 10)
    nColumnes = random.randint(3, 10)

    matriu = MINIM + (random.randint(MAXIM, size = nLinies * nColumnes))
    matriu = matriu.reshape(nLinies, nColumnes)

    mostrarTitul(MATRIUGENERADA + str(index))
    print(matriu)

    mostrarTitul(SUMALINIES)
    sumarLinies(matriu)

    mostrarTitul(SUMACOLUMNES)
    sumarColumnes(matriu)


*************************************
**********MATRIU GENERADA 0**********
*************************************
[[42 32 60  9 61]
 [90 64 12 63 25]
 [23 54 62 22 75]
 [27 79 17 66  2]
 [ 3 35 21 24 98]
 [74 24 94 48 24]
 [63  1  1 88  7]
 [ 2 16 85  9 53]
 [86  9 57 39 27]]
**********************************
**********SUMA DE LÍNIES**********
**********************************
Línia 0 = 204
Línia 1 = 254
Línia 2 = 236
Línia 3 = 191
Línia 4 = 181
Línia 5 = 264
Línia 6 = 160
Línia 7 = 165
Línia 8 = 218
************************************
**********SUMA DE COLUMNES**********
************************************
Columna 0 = 410
Columna 1 = 314
Columna 2 = 409
Columna 3 = 368
Columna 4 = 372
*************************************
**********MATRIU GENERADA 1**********
*************************************
[[43 10 30 14 75]
 [93 16 90  4 32]
 [50  7 17 72 29]
 [47 72 10 49 28]
 [81 22 61 36 46]
 [89 88 86  8 11]
 [25 51  0 89 32]
 [76 61 63 60 27]
 [81 23 63 62 53]]
************************